### ISSUE TITLE
Client pubkey is not authorized

### ISSUE THREAD

**Issue by StefThomas** [centreon/centreon-gorgone#105]
Hi,

On a fresh 20.10 install (on CentOS 7) with a central, a remote  and a poller. Whatever the poller is linked to the remote or not, I have the following error in _gorgoned.log_ on the poller :

`2021-01-28 15:40:05 - ERROR - [core] Client pubkey is not authorized. Thumbprint is 'FbOSChJam7KbVlNzDazwAc2oBhjaRl72SALZ4DKkPME'`

In the file _/etc/centreon-gorgone/config.d/40-gorgoned.yaml_ of both the poller and the remote I see :

```
    authorized_clients: 
      - key: ASotzqxvvcktxS-jb88Y2biEznHOAzpoaJpPxCDla6I
```

Both poller and remote have this same key authorized, and it’s not the same that the one displayed in the error message. There is no such key authorization on the central.

Do you think I should add the offending key in "authorized_clients:" on both the poller and the remote?

What do you think is wrong there ?

**Comment by garnier-quentin** [comment]
Have you tried to add that thumbprint ?
```
authorized_clients: 
      - key: ASotzqxvvcktxS-jb88Y2biEznHOAzpoaJpPxCDla6I
      - key: FbOSChJam7KbVlNzDazwAc2oBhjaRl72SALZ4DKkPME
```

**Comment by StefThomas** [comment]
Yes it works fine after I added the key in 40-gorgoned.yaml on the poller. The other error message I had on the remote also disapeared :

```
2021-01-28 16:19:05 - ERROR - [proxy] Receiving DIE: FATAL: rsa_decrypt_key_ex failed: Invalid input packet. at /usr/share/perl5/vendor_perl/gorgone/standard/library.pm line 260.

2021-01-28 16:19:05 - ERROR - [proxy] Send message problem for '2': Decoding issue: FATAL: rsa_decrypt_key_ex failed: Invalid input packet. at /usr/share/perl5/vendor_perl/gorgone/standard/library.pm line 260.
```

Now I can try to make the host discovering thing to work.

There is still one problem imo, it is that this key I added, is not present in the Gorgone config file I got from the UI (I just verified). So this issue should be kept open I think.

Last thing, I upgraded Gorgoned to unstable  as requested by the support, so I now speak for :

```
centreon-gorgone-20.10.2-1609852578.47515eb.el7.centos.noarch
centreon-gorgone-centreon-config-20.10.2-1609852578.47515eb.el7.centos.noarch
```

**Comment by garnier-quentin** [comment]
You use a old version of gorgone (it seems). Could you do update ? (poller and central)

**Comment by StefThomas** [comment]
This is the last packages available in the unstable Centreon repository. I installed from packages, not from Git.

**Comment by garnier-quentin** [comment]
It's the last also on your poller ?

**Comment by garnier-quentin** [comment]
It seems like it's an issue of centreon interface maybe (not gorgone).
