### ISSUE TITLE
Gorgoned proxy service not starting. 

### ISSUE THREAD

**Issue by pascalbash** [centreon/centreon-gorgone#119]
Hi:

Been using Centreon for quite some time updating my platform regularly to keep up to date, so I consider myself to be fairly familiar with the process.
I just updated Centreon from 19.04 to 20.10 following the official documentation found here:

https://docs.centreon.com/20.10/en/upgrade/upgrade-from-19-04.html

Carefully following every step (copy/paste), the install goes perfectly fine with no errors.  But when I try to push out my configs to any poller I noticed that no configs were being deployed.  Because I had a snapshot of my VM, I have repeated the update  process 3 times so I am sure I did not miss any of the steps.

In reading documentation, I found that gorgoned is the one responsible for this task, so I noticed that the proxy service for gorgoned does not start:

/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/
 **systemctl status gorgoned**
 gorgoned.service - Centreon Gorgone
   Loaded: loaded (/etc/systemd/system/gorgoned.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2021-04-16 00:19:51 EDT; 21s ago
 Main PID: 16270 (perl)
   CGroup: /system.slice/gorgoned.service
           16270 /usr/bin/perl /usr/bin/gorgoned --config=/etc/centreon-gorgone/config.yaml --logfile=/var/log/centreon-gorgone/gorgoned.log --severity=info
           16278 gorgone-nodes
           16280 gorgone-dbcleaner
           16292 gorgone-autodiscovery
           16299 gorgone-cron
           16306 gorgone-engine
           16313 gorgone-statistics
           16320 gorgone-action
           16327 gorgone-httpserver
           16328 gorgone-legacycmd

/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/

From what I read online, I should be seeing this:

/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/
**systemctl status gorgoned**
 gorgoned.service - Centreon Gorgone
   Loaded: loaded (/etc/systemd/system/gorgoned.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2021-04-16 00:21:44 EDT; 6s ago
 Main PID: 31884 (perl)
   CGroup: /system.slice/gorgoned.service
           31884 /usr/bin/perl /usr/bin/gorgoned --config=/etc/centreon-gorgone/config.yaml --logfile=/var/log/centreon-gorgone/gorgoned.log --severity=debug
           31891 gorgone-nodes
           31892 gorgone-dbcleaner
           31899 gorgone-autodiscovery
           31912 gorgone-cron
           31913 gorgone-engine
           31914 gorgone-statistics
           31915 gorgone-action
           31916 gorgone-httpserver
           31917 gorgone-legacycmd
           **31949 gorgone-proxy
           31956 gorgone-proxy
           31957 gorgone-proxy
           31964 gorgone-proxy
           31969 gorgone-proxy**

/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/

But in my case (above) I don't have any of the **proxy services**

I then put the gorgone logs in debug mode (from GUI) and then I restarted the gorgoned service
to see the initialization sequence and I am seeing this:.

/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/
2021-04-15 18:15:54 - INFO - [core] Module 'nodes' is loaded
2021-04-15 18:15:54 - INFO - [core] Module 'proxy' is loading
2021-04-15 18:15:54 - INFO - [core] **Module 'proxy' cannot be loaded: Bareword "SSH_FILEXFER_TYPE_SPECIAL" not allowed while "strict subs" in use at /usr/share/perl5/vendor_perl/gorgone/modules/core/proxy/sshclient.pm line 328.**
Compilation failed in require at /usr/share/perl5/vendor_perl/gorgone/modules/core/proxy/class.pm line 30.
BEGIN failed--compilation aborted at /usr/share/perl5/vendor_perl/gorgone/modules/core/proxy/class.pm line 30.
Compilation failed in require at /usr/share/perl5/vendor_perl/gorgone/modules/core/proxy/hooks.pm line 30.
BEGIN failed--compilation aborted at /usr/share/perl5/vendor_perl/gorgone/modules/core/proxy/hooks.pm line 30.
Compilation failed in require at /usr/share/perl5/vendor_perl/gorgone/class/core.pm line 328.
/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/

Been looking at the code of sshclient.pm but have not been able to figure out where this is coming from

My settings are:

Operating System: CentOS 7

rpm extract:

/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/
$ rpm -qa | grep centreon
centreon-release-20.10-2.el7.centos.noarch
centreon-common-20.10.5-20.el7.centos.noarch
centreon-perl-libs-20.10.5-20.el7.centos.noarch
centreon-connector-perl-20.10.0-2.el7.centos.x86_64
centreon-plugin-Applications-Protocol-Http-20210317-091111.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20210317-091111.el7.centos.noarch
centreon-gorgone-20.10.3-1.el7.centos.noarch
centreon-license-manager-20.10.2-1.el7.centos.noarch
centreon-widget-graph-monitoring-20.10.0-5.el7.centos.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20210317-091111.el7.centos.noarch
centreon-broker-20.10.3-5.el7.centos.x86_64
centreon-broker-core-20.10.3-5.el7.centos.x86_64
centreon-engine-extcommands-20.10.2-2.el7.centos.x86_64
centreon-plugin-Applications-Monitoring-Centreon-Central-20210317-091111.el7.centos.noarch
centreon-widget-tactical-overview-20.10.0-5.el7.centos.noarch
centreon-widget-servicegroup-monitoring-20.10.0-5.el7.centos.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20210317-091111.el7.centos.noarch
centreon-clib-20.10.0-2.el7.centos.x86_64
centreon-broker-cbd-20.10.3-5.el7.centos.x86_64
centreon-connector-20.10.0-2.el7.centos.x86_64
centreon-plugin-Applications-Monitoring-Centreon-Poller-20210317-091111.el7.centos.noarch
centreon-plugin-Applications-Databases-Mysql-20210317-091111.el7.centos.noarch
centreon-auto-discovery-server-20.10.3-2.el7.centos.noarch
centreon-widget-hostgroup-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-live-top10-memory-usage-20.10.0-5.el7.centos.noarch
centreon-widget-service-monitoring-20.10.0-5.el7.centos.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20210317-091111.el7.centos.noarch
centreon-base-config-centreon-engine-20.10.5-20.el7.centos.noarch
centreon-broker-cbmod-20.10.3-5.el7.centos.x86_64
centreon-connector-ssh-20.10.0-2.el7.centos.x86_64
centreon-plugin-Applications-Protocol-Ftp-20210317-091111.el7.centos.noarch
centreon-plugin-Applications-Protocol-Dns-20210317-091111.el7.centos.noarch
centreon-gorgone-centreon-config-20.10.3-1.el7.centos.noarch
centreon-pp-manager-20.10.1-3.el7.centos.noarch
centreon-widget-httploader-20.10.0-5.el7.centos.noarch
centreon-widget-host-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-engine-status-20.10.0-5.el7.centos.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20210317-091111.el7.centos.noarch
centreon-poller-centreon-engine-20.10.5-20.el7.centos.noarch
centreon-broker-storage-20.10.3-5.el7.centos.x86_64
centreon-engine-20.10.2-2.el7.centos.x86_64
centreon-license-manager-common-20.10.2-1.el7.centos.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20210317-091111.el7.centos.noarch
centreon-plugin-Applications-Protocol-Ldap-20210317-091111.el7.centos.noarch
centreon-widget-grid-map-20.10.0-5.el7.centos.noarch
centreon-widget-global-health-20.10.0-5.el7.centos.noarch
centreon-trap-20.10.5-20.el7.centos.noarch
centreon-engine-daemon-20.10.2-2.el7.centos.x86_64
centreon-database-20.10.5-20.el7.centos.noarch
centreon-web-20.10.5-20.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-20.10.0-5.el7.centos.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20210317-091111.el7.centos.noarch
centreon-20.10.5-20.el7.centos.noarch
/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/

And my gorgone config (unmodified from install) is:

/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/
 $ cat /etc/centreon-gorgone/config.d/40-gorgoned.yaml
gorgone:
  gorgonecore:
    privkey: "/var/lib/centreon-gorgone/.keys/rsakey.priv.pem"
    pubkey: "/var/lib/centreon-gorgone/.keys/rsakey.pub.pem"

  modules:
    - name: httpserver
      package: "gorgone::modules::core::httpserver::hooks"
      enable: true
      address: "0.0.0.0"
      port: "8085"
      ssl: false
      auth:
        enabled: false
      allowed_hosts:
        enabled: true
        subnets:
          - 127.0.0.1/32

    - name: action
      package: "gorgone::modules::core::action::hooks"
      enable: true

    - name: cron
      package: "gorgone::modules::core::cron::hooks"
      enable: true
      cron: !include cron.d/*.yaml

    - name: nodes
      package: "gorgone::modules::centreon::nodes::hooks"
      enable: true

    - name: proxy
      package: "gorgone::modules::core::proxy::hooks"
      enable: true

    - name: legacycmd
      package: "gorgone::modules::centreon::legacycmd::hooks"
      enable: true
      cmd_dir: "/var/lib/centreon/centcore/"
      cmd_file: "/var/lib/centreon/centcore.cmd"
      cache_dir: "/var/cache/centreon"
      cache_dir_trap: "/etc/snmp/centreon_traps"
      remote_dir: "/var/cache/centreon/config/remote-data/"

    - name: engine
      package: "gorgone::modules::centreon::engine::hooks"
      enable: true
      command_file: ""

    - name: statistics
      package: "gorgone::modules::centreon::statistics::hooks"
      enable: true
      broker_cache_dir: "/var/cache/centreon/broker-stats/"
      cron:
        - id: broker_stats
          timespec: "*/5 * * * *"
          action: BROKERSTATS
          parameters:
            timeout: 10
        - id: engine_stats
          timespec: "*/5 * * * *"
          action: ENGINESTATS
          parameters:
            timeout: 10
/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/

Would greatly appreciate any help.

Thanks a lot

**Comment by garnier-quentin** [comment]
You need to update that library:
```yum upate perl-Libssh-Session```

then restart gorgoned.

**Comment by pascalbash** [comment]
### AWESOME ! ! ! ! ! !

This solved my problem, I now see my proxy services and my configs are now getting deployed.

/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/
systemctl status gorgoned
 gorgoned.service - Centreon Gorgone
   Loaded: loaded (/etc/systemd/system/gorgoned.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2021-04-16 09:31:01 EDT; 5min ago
 Main PID: 32717 (perl)
   CGroup: /system.slice/gorgoned.service
             305 gorgone-httpserver
             306 gorgone-legacycmd
             **319 gorgone-proxy
             320 gorgone-proxy
             321 gorgone-proxy
             328 gorgone-proxy
             335 gorgone-proxy**
           32717 /usr/bin/perl /usr/bin/gorgoned --config=/etc/centreon-gorgone/config.yaml --logfile=/var/log/centreon-gorgone/gorgoned.log --severity=info
           32724 gorgone-nodes
           32725 gorgone-dbcleaner
           32738 gorgone-autodiscovery
           32743 gorgone-cron
           32752 gorgone-engine
           32759 gorgone-statistics
           32766 gorgone-action
/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/=/

Thanks a lot for your quick response and for the great work you guys
do with Centreon.

**Comment by garnier-quentin** [comment]
thanks for the feedback!
