### ISSUE TITLE
gorgone api only returns no_log for finished gorgone_actions and wrong response for internal endpoints

### ISSUE THREAD

**Issue by rmorandell-pgum** [centreon/centreon-gorgone#133]
Hi,

in the morning the gorgone api was in a very strange state. This has happened for the second time.

He still takes actions and replies immediately with a token, but this token can never be queried. The answer is always "no_log". I then sent a TestCommand that just writes a text into a file. This works, but you don't get an answer via token.

`curl --request POST "http://localhost:8085/api/core/action/command" \
  --header "Accept: application/json" \
  --header "Content-Type: application/json" \
  --data "[
    {
        \"command\": \"echo 'Test command' >> /tmp/foo.dat\"
    }
]"

{"token":"d66b6d2e211f24fd57617083ee8f8172bb26cb63b00da73462f1e77ab9b62e05ac1d4817d18df87937d9bfc0588e64e9feebbc3fd8b8f733faca96d29266ff25"}

 cat /tmp/foo.dat
Test command

curl --request GET "http://localhost:8085/api/log/d66b6d2e211f24fd57617083ee8f8172bb26cb63b00da73462f1e77ab9b62e05ac1d4817d18df87937d9bfc0588e64e9feebbc3fd8b8f733faca96d29266ff25" --header "Accept: application/json"

 curl --request GET "http://localhost:8085/api/log/d66b6d2e211f24fd57617083ee8f8172bb26cb63b00da73462f1e77ab9b62e05ac1d4817d18df87937d9bfc0588e64e9feebbc3fd8b8f733faca96d29266ff25" --header "Accept: application/json"
**{"error":"no_log","message":"No log found for token",**"data":[],"token":"d66b6d2e211f24fd57617083ee8f8172bb26cb63b00da73462f1e77ab9b62e05ac1d4817d18df87937d9bfc0588e64e9feebbc3fd8b8f733faca96d29266ff25"}`

I then called the internal endpoints "/ internal / constatus" and as a response I get "action": "getlog"

curl --request GET "http://localhost:8085/api/internal/constatus"  --header "Accept: application/json"
{"action":"getlog","id":"1","result":[{"ctime":1623308283.12307,"etime":1623308283,"id":"10003856","instant":0,"data":"{\"action\":\"constatus\",\"data\":{\"11\":{\"last_ping_sent\":1623308224,\"nodes\":{},\"type\":\"push_zmq\",\"last_ping_recv\":1623308224},\"7\":{\"last_ping_sent\":1623308224,\"nodes\":null,\"type\":\"push_ssh\",\"last_ping_recv\":1623308224},\"17\":{\"last_ping_sent\":1623308224,\"nodes\":null,\"type\":\"push_ssh\",\"last_ping_recv\":1623308224},\"2\":{\"last_ping_sent\":1623308224,\"nodes\":{},\"type\":\"push_zmq\",\"last_ping_recv\":1623308224},\"18\":{\"last_ping_sent\":1623308224,\"nodes\":null,\"type\":\"push_ssh\",\"last_ping_recv\":1623308224},\"16\":{\"last_ping_sent\":1623308224,\"nodes\":null,\"type\":\"push_ssh\",\"last_ping_recv\":1623308224},\"13\":{\"last_ping_sent\":1623308224,\"nodes\":null,\"type\":\"push_ssh\",\"last_ping_recv\":1623308224},\"6\":{\"last_ping_sent\":1623308224,\"nodes\":null,\"type\":\"push_ssh\",\"last_ping_recv\":1623308224},\"9\":{\"last_ping_sent\":1623308224,\"nodes\":null,\"type\":\"push_ssh\",\"last_ping_recv\":1623308224},\"12\":{\"last_ping_sent\":1623308224,\"nodes\":null,\"type\":\"push_ssh\",\"last_ping_recv\":1623308224},\"14\":{\"last_ping_sent\":1623308224,\"nodes\":null,\"type\":\"push_ssh\",\"last_ping_recv\":1623308224},\"15\":{\"last_ping_sent\":1623308224,\"nodes\":null,\"type\":\"push_ssh\",\"last_ping_recv\":1623308224},\"8\":{\"last_ping_sent\":1623308224,\"nodes\":null,\"type\":\"push_ssh\",\"last_ping_recv\":1623308224},\"4\":{\"last_ping_sent\":1623308224,\"nodes\":null,\"type\":\"push_ssh\",\"last_ping_recv\":1623308224},\"19\":{\"last_ping_sent\":1623308224,\"nodes\":null,\"type\":\"push_ssh\",\"last_ping_recv\":1623308224},\"10\":{\"last_ping_sent\":1623308224,\"nodes\":{},\"type\":\"push_zmq\",\"last_ping_recv\":1623308224},\"5\":{\"last_ping_sent\":1623308224,\"nodes\":null,\"type\":\"push_ssh\",\"last_ping_recv\":1623308224}},\"message\":\"ok\"}","token":"0fe6229443cd58639ab1d7ebc06e641f9089860ed8255e9c9bcdca888e781c48d62a259e9b51e55de39043ed4829cd27e2f9b347400caa59758da70d6a33c1e0","code":2}]}

at the endpoint "/ internal / information" I get the response "action": "constatus"

 curl --request GET "http://localhost:8085/api/internal/information" --header "Accept: application/json"
{"action":"constatus","data":{"11":{"last_ping_sent":1623308588,"type":"push_zmq","nodes":{},"last_ping_recv":1623308588},"7":{"last_ping_sent":1623308588,"type":"push_ssh","nodes":null,"last_ping_recv":1623308588},"2":{"last_ping_sent":1623308588,"type":"push_zmq","nodes":{},"last_ping_recv":1623308588},"17":{"last_ping_sent":1623308588,"type":"push_ssh","nodes":null,"last_ping_recv":1623308588},"18":{"last_ping_sent":1623308588,"type":"push_ssh","nodes":null,"last_ping_recv":1623308588},"16":{"last_ping_sent":1623308588,"type":"push_ssh","nodes":null,"last_ping_recv":1623308588},"13":{"last_ping_sent":1623308588,"type":"push_ssh","nodes":null,"last_ping_recv":1623308588},"6":{"last_ping_sent":1623308588,"type":"push_ssh","nodes":null,"last_ping_recv":1623308588},"9":{"last_ping_sent":1623308588,"type":"push_ssh","nodes":null,"last_ping_recv":1623308588},"12":{"last_ping_sent":1623308588,"type":"push_ssh","nodes":null,"last_ping_recv":1623308588},"14":{"last_ping_sent":1623308588,"type":"push_ssh","nodes":null,"last_ping_recv":1623308588},"15":{"last_ping_sent":1623308588,"type":"push_ssh","nodes":null,"last_ping_recv":1623308588},"8":{"last_ping_sent":1623308588,"type":"push_ssh","nodes":null,"last_ping_recv":1623308588},"4":{"last_ping_sent":1623308588,"type":"push_ssh","nodes":null,"last_ping_recv":1623308588},"19":{"last_ping_sent":1623308588,"type":"push_ssh","nodes":null,"last_ping_recv":1623308588},"10":{"last_ping_sent":1623308588,"type":"push_zmq","nodes":{},"last_ping_recv":1623308588},"5":{"last_ping_sent":1623308588,"type":"push_ssh","nodes":null,"last_ping_recv":1623308588}},"message":"ok"}

The centreon-gorgone log is clean and does not contain any errors.

After restarting the gorgone service everything works fine again. What could be causing this?

I'm trying to reproduce this.

We use the latest 20.10.x. 

centreon-20.10.8-5.el7.centos.noarch
centreon-auto-discovery-server-20.10.3-2.el7.centos.noarch
centreon-awie-20.10.0-1.el7.centos.noarch
centreon-base-config-centreon-engine-20.10.8-5.el7.centos.noarch
centreon-broker-20.10.5-2.el7.centos.x86_64
centreon-broker-cbd-20.10.5-2.el7.centos.x86_64
centreon-broker-cbmod-20.10.5-2.el7.centos.x86_64
centreon-broker-core-20.10.5-2.el7.centos.x86_64
centreon-broker-graphite-20.10.5-2.el7.centos.x86_64
centreon-broker-influxdb-20.10.5-2.el7.centos.x86_64
centreon-broker-storage-20.10.5-2.el7.centos.x86_64
centreon-clib-20.10.2-1.el7.centos.x86_64
centreon-common-20.10.8-5.el7.centos.noarch
centreon-connector-20.10.1-1.el7.centos.x86_64
centreon-connector-perl-20.10.1-1.el7.centos.x86_64
centreon-connector-ssh-20.10.1-1.el7.centos.x86_64
centreon-database-20.10.8-5.el7.centos.noarch
centreon-engine-20.10.5-3.el7.centos.x86_64
centreon-engine-daemon-20.10.5-3.el7.centos.x86_64
centreon-engine-extcommands-20.10.5-3.el7.centos.x86_64
centreon-fingerprint-20.10.0-2.el7.centos.x86_64
centreon-gorgone-20.10.3-1.el7.centos.noarch
centreon-gorgone-centreon-config-20.10.3-1.el7.centos.noarch
centreon-license-manager-20.10.3-3.el7.centos.noarch
centreon-license-manager-common-20.10.3-3.el7.centos.noarch
centreon-open-tickets-20.10.2-1.el7.centos.noarch
centreon-perl-libs-20.10.8-5.el7.centos.noarch
centreon-poller-centreon-engine-20.10.8-5.el7.centos.noarch
centreon-pp-manager-20.10.1-3.el7.centos.noarch
centreon-release-20.10-2.el7.centos.noarch
centreon-trap-20.10.8-5.el7.centos.noarch
centreon-web-20.10.8-5.el7.centos.noarch
centreon-widget-engine-status-20.10.0-5.el7.centos.noarch
centreon-widget-global-health-20.10.0-5.el7.centos.noarch
centreon-widget-graph-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-grid-map-20.10.0-5.el7.centos.noarch
centreon-widget-hostgroup-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-host-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-httploader-20.10.0-5.el7.centos.noarch
centreon-widget-live-top10-cpu-usage-20.10.0-5.el7.centos.noarch
centreon-widget-live-top10-memory-usage-20.10.0-5.el7.centos.noarch
centreon-widget-servicegroup-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-service-monitoring-20.10.0-5.el7.centos.noarch
centreon-widget-tactical-overview-20.10.0-5.el7.centos.noarch

**Comment by garnier-quentin** [comment]
When you have the no_log. Could you check your sqlite gorgone database ?

**Comment by garnier-quentin** [comment]
I have fixed an issue about that. Maybe it's not in 20.10.3. It will be in next release for sure.

**Comment by rmorandell-pgum** [comment]
Yes the token is in the db but it seems that the tokens are mixed up.

My request was ..

```
curl --request POST "http://localhost:8085/api/core/action/command"
--header "Accept: application/json"
--header "Content-Type: application/json"
--data "[
{
"command": "echo 'Test command' >> /tmp/foo.dat"
}
]"

{"token":"d66b6d2e211f24fd57617083ee8f8172bb26cb63b00da73462f1e77ab9b62e05ac1d4817d18df87937d9bfc0588e64e9feebbc3fd8b8f733faca96d29266ff25"}
```

When i was asking with this token for the log ..

```
curl --request GET "http://localhost:8085/api/log/d66b6d2e211f24fd57617083ee8f8172bb26cb63b00da73462f1e77ab9b62e05ac1d4817d18df87937d9bfc0588e64e9feebbc3fd8b8f733faca96d29266ff25" --header "Accept: application/json"
{"error":"no_log","message":"No log found for token","data":[],"token":"d66b6d2e211f24fd57617083ee8f8172bb26cb63b00da73462f1e77ab9b62e05ac1d4817d18df87937d9bfc0588e64e9feebbc3fd8b8f733faca96d29266ff25"}`
```

in the db searching for this token seems a request with action "constatus" that i've done later 

```
sqlite>  select * from gorgone_history where token = 'd66b6d2e211f24fd57617083ee8f8172bb26cb63b00da73462f1e77ab9b62e05ac1d4817d18df87937d9bfc0588e64e9feebbc3fd8b8f733faca96d29266ff25';
     id = 10004377
  token = d66b6d2e211f24fd57617083ee8f8172bb26cb63b00da73462f1e77ab9b62e05ac1d4817d18df87937d9bfc0588e64e9feebbc3fd8b8f733faca96d29266ff25
   code = 2
  etime = 1623309003
  ctime = 1623309003.19331
instant = 0
   data = {"action":"constatus","data":{"11":{"last_ping_sent":1623308983,"nodes":{},"type":"push_zmq","last_ping_recv":1623309000},"7":{"last_ping_sent":1623308983,"nodes":null,"type":"push_ssh","last_ping_recv":1623308983},"17":{"last_ping_sent":1623308983,"nodes":null,"type":"push_ssh","last_ping_recv":1623308983},"2":{"last_ping_sent":1623308983,"nodes":{},"type":"push_zmq","last_ping_recv":1623309001},"18":{"last_ping_sent":1623308983,"nodes":null,"type":"push_ssh","last_ping_recv":1623308983},"16":{"last_ping_sent":1623308983,"nodes":null,"type":"push_ssh","last_ping_recv":1623308983},"13":{"last_ping_sent":1623308983,"nodes":null,"type":"push_ssh","last_ping_recv":1623308983},"6":{"last_ping_sent":1623308983,"nodes":null,"type":"push_ssh","last_ping_recv":1623308983},"9":{"last_ping_sent":1623308983,"nodes":null,"type":"push_ssh","last_ping_recv":1623308983},"12":{"last_ping_sent":1623308983,"nodes":null,"type":"push_ssh","last_ping_recv":1623308983},"14":{"last_ping_sent":1623308983,"nodes":null,"type":"push_ssh","last_ping_recv":1623308983},"15":{"last_ping_sent":1623308983,"nodes":null,"type":"push_ssh","last_ping_recv":1623308983},"8":{"last_ping_sent":1623308983,"nodes":null,"type":"push_ssh","last_ping_recv":1623308983},"4":{"last_ping_sent":1623308983,"nodes":null,"type":"push_ssh","last_ping_recv":1623308983},"19":{"last_ping_sent":1623308983,"nodes":null,"type":"push_ssh","last_ping_recv":1623308983},"10":{"last_ping_sent":1623308983,"nodes":{},"type":"push_zmq","last_ping_recv":1623309001},"5":{"last_ping_sent":1623308983,"nodes":null,"type":"push_ssh","last_ping_recv":1623308983}},"message":"ok"}
```

**Comment by garnier-quentin** [comment]
It already fixed i think. You can use the unstable.

**Comment by rmorandell-pgum** [comment]
ok thanks

**Comment by rmorandell-pgum** [comment]
Hi,

the fix is just included in 20.10.4 released yesterday ?

Thanks for info

**Comment by garnier-quentin** [comment]
Yes i think

**Comment by rmorandell-pgum** [comment]
Hi,
unfortunately, the problem still occurs. I installed the 10/20.4 and restarted.

I simulate the problem by sending 100 action commands every 10 minutes that just write the action number in a file and keep the tokens for me. Then I ask all tokens to see if all commands have been completed.

After a while the actions are still being carried out and I can see that in the sqlite3 history, but when I do getlog I always get no_log back

```
 curl --request GET "http://localhost:8085/api/log/966eddc7344dcbca9e4ace336be072e2c7da01a39000fdf8460bd61262c39f3ecb689fbf29b6c2031d13a2ec7d9728c981e8f64944594af0fff4a16e4e396542" --header "Accept: application/json"
{"error":"no_log","message":"No log found for token","data":[],"token":"966eddc7344dcbca9e4ace336be072e2c7da01a39000fdf8460bd61262c39f3ecb689fbf29b6c2031d13a2ec7d9728c981e8f64944594af0fff4a16e4e396542"}
```

the gorgone_history in sqlite shows me that the command is executed and terminated successfully.

```
SQLite version 3.7.17 2013-05-20 00:56:22
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> .mode line
sqlite>  select * from gorgone_history where token = '966eddc7344dcbca9e4ace336be072e2c7da01a39000fdf8460bd61262c39f3ecb689fbf29b6c2031d13a2ec7d9728c981e8f64944594af0fff4a16e4e396542';
     id = 10504761
  token = 966eddc7344dcbca9e4ace336be072e2c7da01a39000fdf8460bd61262c39f3ecb689fbf29b6c2031d13a2ec7d9728c981e8f64944594af0fff4a16e4e396542
   code = 0
  etime = 1623748201
  ctime = 1623748201.42414
instant = 0
   data = {"message":"commands processing has started","request_content":[{"timeout":30,"command":"echo 'action number 1 ..' >> /tmp/foo.dat"}]}

     id = 10504767
  token = 966eddc7344dcbca9e4ace336be072e2c7da01a39000fdf8460bd61262c39f3ecb689fbf29b6c2031d13a2ec7d9728c981e8f64944594af0fff4a16e4e396542
   code = 0
  etime = 1623748201
  ctime = 1623748201.51265
instant = 0
   data = {"metadata":null,"message":"command has started","command":"echo 'action number 1 ..' >> /tmp/foo.dat"}

     id = 10504776
  token = 966eddc7344dcbca9e4ace336be072e2c7da01a39000fdf8460bd61262c39f3ecb689fbf29b6c2031d13a2ec7d9728c981e8f64944594af0fff4a16e4e396542
   code = 100
  etime = 1623748201
  ctime = 1623748201.59683
instant = 0
   data = {"metadata":null,"metrics":{"duration":0,"start":1623748201,"end":1623748201},"message":"command has finished successfully","command":"echo 'action number 1 ..' >> /tmp/foo.dat","result":{"exit_code":0,"stdout":""}}

     id = 10504784
  token = 966eddc7344dcbca9e4ace336be072e2c7da01a39000fdf8460bd61262c39f3ecb689fbf29b6c2031d13a2ec7d9728c981e8f64944594af0fff4a16e4e396542
   code = 2
  etime = 1623748201
  ctime = 1623748201.72152
instant = 0
   data = {"message":"commands processing has finished successfully"}
```

After that, the other endpoints will also work, e.g. internal no longer

```
 curl --request GET "http://localhost:8085/api/internal/information" --header "Accept: application/json"
{"error":"no_result", "message":"No result found for action 'INFORMATION'"}
```

Thanks for your help

**Comment by rmorandell-pgum** [comment]
For info: now in the new version the first time i'm getting always a "no_log" error the first try. Even if the first request for log is after a minute after sending the command. The second try is returning me the result

**Comment by garnier-quentin** [comment]
I will take a look

**Comment by garnier-quentin** [comment]
I have done the patch. You can test it with unstable version or you can apply it:
https://github.com/centreon/centreon-gorgone/pull/134/files

**Comment by rmorandell-pgum** [comment]
ok thanks i'll try it

**Comment by rmorandell-pgum** [comment]
sorry for the late response. The fix is working fine !! Thanks
