### ISSUE TITLE
Deleted poller still in Gorgone Database

### ISSUE THREAD

**Issue by cmey84** [centreon/centreon-gorgone#162]
Hello,

I just noticed an issue in poller configuration, deleted poller are still present in Gorgone database in "gorgone_target_fingerprint" table.
I noticed it checking Firewalls log because the Central keep sending request to the deleted poller  and i don't know how to stop it.

So do you have a way to properly clean the database ?

Bests,

**Comment by garnier-quentin** [comment]
Gorgone syncs each 10 minutes. Or you can restart gorgoned daemon on your central server.

**Comment by cmey84** [comment]
The poller were deleted months ago, and since i tried to restart the daemon or server multiple time but nothing change.

**Comment by garnier-quentin** [comment]
Yes the fingerprint can still be in ```gorgone_target_fingerprint``` table. But it don't use that to connect on your deleted poller.

**Comment by cmey84** [comment]
Just did it, and no trace of the requests in gorgone log but i'm still seeing them in firewall log every minutes on port 5669

**Comment by garnier-quentin** [comment]
The port 5669 is for centreon-broker.

**Comment by cmey84** [comment]
Just checked and i had an issue with the broker configuration, it's ok now.

Thanks for your help :)

**Comment by garnier-quentin** [comment]
You're welcome. Thanks for the feedback!
