### ISSUE TITLE
Configuration : "!include" keywork not work

### ISSUE THREAD

**Issue by xNatek** [centreon/centreon-gorgone#23]
Hi!

Tested on Ubuntu 20.04, with Perl v5.30.0.

Function  YAML::XS::LoadFile remove "!include" keyword from configuration file and parse it like a string :

`Can't use string ("config.d/*.yaml") as a HASH ref while "strict refs" in use at /usr/share/perl5/gorgone/class/core.pm line 84.`

Best Regards,

**Comment by garnier-quentin** [comment]
Could you provide me your files and directories ? (can be done by email) I could try to reproduce.

**Comment by xNatek** [comment]
I'm using the default configuration file without changes:

`name: "config.yaml"
description: Configuration brought by Centreon Gorgone
configuration: !include /etc/centreon-gorgone/config.d/*.yaml`

Each time the keyword "!include" is used in YAML, it's removed par the YAML::XS parser (same case with 'cron: !include cron.d/*.yaml')

- OS : Ubuntu 20.04 LTS
- Perl : v5.30.0 x86_64-linux-gnu-thread-multi
- YAML.pm : v1.30
- YAML/XS.pm : v0.81

Would you like more informations by email ?

**Comment by garnier-quentin** [comment]
Yes. i need your config files and directories.

**Comment by xNatek** [comment]
Configuration send by email.

**Comment by garnier-quentin** [comment]
Ok it comes from the last version:
```
0.81 Mon 27 Jan 2020 11:05:46 PM CET
Breaking Change: Set $YAML::XS::LoadBlessed default to false to make it
   more secure

**Comment by garnier-quentin** [comment]
you can test with last version.
