### ISSUE TITLE
[22.04] Use of uninitialized value in numeric lt (<) at /usr/share/perl5/vendor_perl/gorgone/class/core.pm line 788.

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-gorgone#237]
Hello,

I have upgrade my poller version 21.10.6 to 22.04 (Redhat) and i have this error after upgrade in /var/log/centreon-gorgone : 

`Use of uninitialized value in numeric lt (<) at /usr/share/perl5/vendor_perl/gorgone/class/core.pm line 788.`

I have reboot my server and apply all update with no result.

Do you have a solution ?

Thank you

**Comment by garnier-quentin** [comment]
Does it block the connection ?

**Comment by garnier-quentin** [comment]
Could you patch it ? https://github.com/centreon/centreon-gorgone/pull/238

**Comment by prohand** [comment]
Do you have a procedure for patch ;)

Thank you

**Comment by garnier-quentin** [comment]
You change the file directly (only one line to change) and you restart gorgoned.

**Comment by prohand** [comment]
Hello,

It's OK thank you.

The problem is solved
