### ISSUE TITLE
Gorgone unstable Can't use bareword ("self")

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-gorgone#29]
Hello,

I update centreon-gorgone with this issues : 

https://github.com/centreon/centreon-engine/issues/384

yum --enablerepo="centreon-unstable*" update centreon-gorgone

And the proxy node is not created : 

`service gorgoned status
Redirecting to /bin/systemctl status gorgoned.service
● gorgoned.service - Centreon Gorgone
   Loaded: loaded (/etc/systemd/system/gorgoned.service; enabled; vendor preset: disabled)
   Active: active (running) since mer. 2020-05-06 21:08:34 CEST; 3min 34s ago
 Main PID: 678 (perl)
   CGroup: /system.slice/gorgoned.service
           ├─678 /usr/bin/perl /usr/bin/gorgoned --config=/etc/centreon-gorgone/config.yaml --logfile=/var/log/centreon-gorgone/gorgoned.log --severity=info
           ├─688 gorgone-nodes
           ├─690 gorgone-dbcleaner
           ├─702 gorgone-autodiscovery
           ├─709 gorgone-cron
           ├─716 gorgone-engine
           ├─723 gorgone-statistics
           ├─730 gorgone-action
           ├─737 gorgone-httpserver
           └─738 gorgone-legacycmd
`

Error log in gorgoned.log : 

```
 [core] Module 'proxy' cannot be loaded: Can't use bareword ("self") as a HASH ref while "strict refs" in use at /usr/share/perl5/vendor_perl/gorgone/modules/core/proxy/class.pm line 237.
Compilation failed in require at /usr/share/perl5/vendor_perl/gorgone/modules/core/proxy/hooks.pm line 29.
BEGIN failed--compilation aborted at /usr/share/perl5/vendor_perl/gorgone/modules/core/proxy/hooks.pm line 29.
Compilation failed in require at /usr/share/perl5/vendor_perl/gorgone/class/core.pm line 306.

```
Thank you

**Comment by garnier-quentin** [comment]
i have fixed it. you can update with the same command:
```
yum --enablerepo="centreon-unstable*" clean all
yum --enablerepo="centreon-unstable*" update centreon-gorgone
```

**Comment by prohand** [comment]
It's ok.
Thank you :)
