### ISSUE TITLE
Gorgoned daemon stop regulary doing his job

### ISSUE THREAD

**Issue by fixlair** [centreon/centreon-gorgone#36]
Hi !
Thanks for your work with Gorgone! We just update our platform on Centreon 20.04 and Gorgone 20.04.3 (Centos7). We do have 13 pollers we faced to a random problem with gorgoned stop working properly.

**Symptoms**: Ack, Poller Reload, Dowtime, etc from Central poller stop working after a random amount of time without letting any specific message (on Gorgone Central or on the poller) (even with "Debug" log level). The gorgone Process is still running on Remote and Central. The command is seend on Gorgone log on Central but neither in the gorgone log of the remote poller.

We did see this kind of messages on Gorgone process of the Central server when this situation occurs: 
`2020-06-24 13:57:21 - ERROR - [proxy] Send message problem for '4':
2020-06-24 13:57:30 - ERROR - [proxy] Send message problem for '2':
2020-06-24 13:57:41 - ERROR - [proxy] Send message problem for '7':`
The ID in this case are poller on wich we were not able to send command on anymore.

**First workarround**: Reload gorgoned on Central and poller (`systemctl restart gorgoned`)
**Second workaround/solution?** applied (wich seems to be working since and no need to first workarround): 
* Update 'pool' of 'proxy' module from the default '5' value to something bigger than the number of poller `/etc/centreon-gorgone/config.d/40-gorgoned.yaml`:
(in our case with 13 poller)
```
- name: proxy
      package: "gorgone::modules::core::proxy::hooks"
      enable: true
      pool: 15
```

=> Is this an expected behaviour? If yes I didn't not see it on Centreon Documentation maybe it's worth to document it?

Regards,

**Comment by garnier-quentin** [comment]
Could you try with the last version ? Without your workaround.
```
yum --enablerepo=centreon-unstable* update centreon-gorgone
systemctl restart gorgoned
```

**Comment by fixlair** [comment]
After switching to unstable I did not met this behaviour since monday. I swiched back to stable.
Strange but as I did not reproduce it, I close the issue for the moment... (with the default package value for number of proxy)

Thanks

**Comment by garnier-quentin** [comment]
Thanks for the feedback!
