### ISSUE TITLE
Poller: ERROR - [proxy] Send message problem for '2'

### ISSUE THREAD

**Issue by joschi99** [centreon/centreon-gorgone#42]
We use latest version 20.04 on CentOS 7.8 (central and poller) with ZMQ enabled. Communication between Central and Poller is working, also configuration export ost working fine.
But on /var/log/centreon-gorgone/gorgoned.log we get this error:

```
2020-08-24 17:38:26 - INFO - [proxy] Send pings
2020-08-24 17:38:36 - ERROR - [proxy] Send message problem for '2':
2020-08-24 17:38:36 - INFO - [proxy] PongReset received from '2'
2020-08-24 17:38:46 - ERROR - [proxy] Send message problem for '2':
2020-08-24 17:38:46 - INFO - [proxy] PongReset received from '2'
```

And if we monitor Gorgone Nodes like
```
/usr/lib/centreon/plugins/centreon_plugins.pl --plugin=apps::gorgone::restapi::plugin --hostname=127.0.0.1 --port=8085 --proto=http --ssl-opt='' --mode=nodes --warning-ping-received-lasttime=900 --critical-ping-received-lasttime=3600
CRITICAL: Node '2' last ping received: 1598283611 s | '2#node.ping.received.lasttime.seconds'=1598283611s;0:900;0:3600;;
```
we have an alert because ping received is very high

**Comment by cgagnaire** [comment]
Hi @joschi99,
It seems your Central can't connect to your Poller.
Can you put the Central's Gorgone in debug from 'Administration > Parameters > Debug' and restart it ?
And then post the full log from the restart to the errors ?
Also, the plugin doesn't handle correctly the nodes that don't communicate, that's why you get a last ping being current timestamp.
You can see the actual status using `curl http://localhost:8085/api/internal/constatus | python -m json.tool`.
Thank you.

**Comment by joschi99** [comment]
curl http://localhost:8085/api/internal/constatus | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   129  100   129    0     0    784      0 --:--:-- --:--:-- --:--:--   786
{
    "action": "constatus",
    "data": {
        "2": {
            "last_ping_recv": 0,
            "last_ping_sent": 1598346419,
            "nodes": {},
            "type": "push_zmq"
        }
    },
    "message": "ok"
}
[gorgoned-debug.log](https://github.com/centreon/centreon-gorgone/files/5122645/gorgoned-debug.log)

**Comment by cgagnaire** [comment]
@joschi99,
Can you apply this doc https://docs.centreon.com/20.04/en/monitoring/monitoring-servers/add-a-poller-to-configuration.html#display-gorgone-configuration ?
And make sure that the authorized clients key is the one specified in the log has "JWK thumbprint" ?
After copying the configuration, and restarting Gorgone on both Poller and Central it should be ok.
If not, we'll need the log from the Poller.

**Comment by joschi99** [comment]
Hi @cgagnaire ,
i have found the issue. the poller firewall configuration for port 5666 was not permanent. Have done now a permanent rule and it is working fine.

Sorry for the inconvenience.

Regards,
Jochen

**Comment by cgagnaire** [comment]
No worries.
