### ISSUE TITLE
Issue with db password used by gorgoned

### ISSUE THREAD

**Issue by alliria98** [centreon/centreon-gorgone#70]
Hi everyone,
I freshly installed a whole new Centreon server in 20.04.4 version
Everything's fine except for ackowledge, force check... things relative to gorgoned.service

I checked the /var/log/centreon-gorgone/gorgoned.log and found an issue to connect to the db

2020-10-28 09:40:14 - ERROR - MySQL error : cannot connect to database 'mysql:host=localhost:3306;dbname=centreon': Access denied for user 'centreon'@'localhost' (using password: YES) (caller: gorgone::class::db:/usr/share/perl5/gorgone/class/db.pm:278) (try: 0)

So I checked the /etc/centreon/config.d/10-database.yaml and found a password for the db "centreon" who come from nowhere
So I edited it with the correct password, and restarted gorgoned.service

No more SQL issues for the service, force check, ackowledge seems to be ok..... but my poller doesn't update anymore.

May you could provide me some help ?

**Comment by alliria98** [comment]
Not yet
I'll probably have to do that. Any tips to do it properly ? Running on debian

**Comment by garnier-quentin** [comment]
You have used source package ?

**Comment by alliria98** [comment]
I followed this thread : https://www.sugarbug.fr/atelier/installations/debian/debian10_centreon_2004/

This is how I downloaded source files :
wget http://files.download.centreon.com/public/centreon-clib/centreon-clib-20.04.0.tar.gz


PS : sorry for my ultra low skills in Linux world :(

**Comment by garnier-quentin** [comment]
You can update gorgone first: https://github.com/centreon/centreon-gorgone/releases/tag/20.04.6

**Comment by alliria98** [comment]
Thanks for the source files
After updating and restarting services, i still have my SQL connection issue for bad password

May should I update centreon's services in 20.10 ?

**Comment by garnier-quentin** [comment]
You say you have fixed the SQL connection issue no ?

**Comment by alliria98** [comment]
I rolled back since fixing this connection issue generate a more important issue on poller

**Comment by alliria98** [comment]
Does updating gorgoned to 20.04.6 has any impact on the poller ?

**Comment by garnier-quentin** [comment]
You also need to update your gorgone poller.

**Comment by alliria98** [comment]
I confirm that update only gorgoned service + edit the file /etc/centreon/config.d/10-database.yaml to change the password won't fix the poller problem
Where/how can I update my gorgone poller ?

**Comment by garnier-quentin** [comment]
It's the same that central server for upgrading gorgone on a poller

**Comment by alliria98** [comment]
Not sure if i understood correctly but I only have 1 server that host all services

**Comment by alliria98** [comment]
I just found out in the log file /var/log/centreon-broker/central-broker-master.log an error (I put back the correct password in /etc/centreon/config.d/10-database.yaml and restarted services. No more gorgoned errors)

Here is the central broker error :
 error:   conflict_manager: error in the main loop: could not prepare insert or update query for event 'comment' in table '': Incorrect string value: '\xE8me su...' for column `centreon_storage`.`logs`.`output` at row 1 (while executing statement 2075038481

Any idea ?

**Comment by garnier-quentin** [comment]
It's not a gorgone issue. And i think it will fixed if you update centreon-broker.

**Comment by garnier-quentin** [comment]
Do you still have the issue ?

**Comment by alliria98** [comment]
Sorry for the very late update about this :
I found the root cause of my problem

Neither the gorgone version nor the db password was in the main cause of this issue, but a snmptrapd / centreontrapd and a passive check i had created around the same time of the issue
the trap was receive by centreon and the output I had configure to show up in that case created a bad entry in the database, making it unreadable anymore

Since I did many rollback I can't say which character was the cause exactly, but probably something like "à" or "é" (French letter with accent on it)

**Comment by garnier-quentin** [comment]
So it's not a gorgone issue. I close it. thanks for the feedback
