### ISSUE TITLE
Special characters in the Gorgone configuration files

### ISSUE THREAD

**Issue by jeanrenemoyap** [centreon/centreon-gorgone#89]
Hi,
Thanks for your work with Gorgone!
I just configure the access to the Centreon APIs located at /etc/centreon-gorgone/config.d/31-centreon-api.yaml
I face a unrecognized clapi username issue.

**Symptoms**: When i run the service discovery, i see the following errors in the gorgoned.log file.

/var/log/centreon-gorgone/gorgoned.log
2020-12-14 11:53:08 - ERROR - [autodiscovery] -servicediscovery- c74eafa9:3 clapi username configuration missing
2020-12-14 11:53:58 - ERROR - [autodiscovery] -class- host discovery - cannot get platform versions - configuration missing

Centreon CLAPI and Rest API access is defined as follows:

/etc/centreon-gorgone/config.d/31-centreon-api.yaml
gorgone:
  tpapi:
    - name: centreonv2
      base_url: "http://127.0.0.1/centreon/api/beta/"
      username: admin
      password: @d1m1n4iXm0n1t0r2016
    - name: clapi
      username: admin
      password: @d1m1n4iXm0n1t0r2016

**Solution**:  I put the password in quotes ""

/etc/centreon-gorgone/config.d/31-centreon-api.yaml
gorgone:
  tpapi:
    - name: centreonv2
      base_url: "http://127.0.0.1/centreon/api/beta/"
      username: admin
      password: "@d1m1n4iXm0n1t0r2016"
    - name: clapi
      username: admin
      password: "@d1m1n4iXm0n1t0r2016"

 It's worth to document it?

**Comment by garnier-quentin** [comment]
Thanks  for the issue.
