### ISSUE TITLE
Reverse ZMQ tcp connection

### ISSUE THREAD

**Issue by TheBlaide** [centreon/centreon-gorgone#96]
Hello,

What would be the configuration in the gorogned files to reverse the ZMQ configuration ? 

For ease of admin purpose (firewall rules and nat), i'd like the central server to listen on port 5556 and our remote poller to initiate the connection on the central server. 

i've tried to use the pull module on the remote poller with no success.

here is the yaml on the poller:

ame:  gorgoned-prod-s01-pp
description: Configuration for poller prod-s01-pp
gorgone:
  gorgonecore:
    id: 178
    external_com_type: tcp
    external_com_path: "*:5556"
    authorized_clients:
      - key: xxxxxxxxxxxxxxx
    privkey: "/var/lib/centreon-gorgone/.keys/rsakey.priv.pem"
    pubkey: "/var/lib/centreon-gorgone/.keys/rsakey.pub.pem"
  modules:
    - name: action
      package: gorgone::modules::core::action::hooks
      enable: true

    - name: engine
      package: gorgone::modules::centreon::engine::hooks
      enable: true
      command_file: ""

    - name: pull
      package: "gorgone::modules::core::pull::hooks"
      enable: true

the running version is 20.10.

Regards,

**Comment by garnier-quentin** [comment]
Have you looked that file ? https://github.com/centreon/centreon-gorgone/blob/master/docs/poller_pull_configuration.md

**Comment by TheBlaide** [comment]
Whoa thanks for your quick reply.

is there a way not to specify all the remote nodes in the register overrride yml file  ?

like a wild card since all our remote poller will use the same configuration.

Regards,

**Comment by garnier-quentin** [comment]
You need to specify it if you use 'centreon' nodes module.

**Comment by TheBlaide** [comment]
Hello Quentin,
the centreon nodes module is loaded by this bock right ? 

    - name: nodes
      package: "gorgone::modules::centreon::nodes::hooks"
      enable: true

is it possible to remove this block and remove the override.yml files in order to simplify the configuration ? 

what would be the fonctional impact without the centreon node module ? 

Regards,

Blaise

**Comment by garnier-quentin** [comment]
Yes it's the configuration for modules 'nodes'. You can remove it. But if you remove it, you won't have configuration to connect on your pollers.
